### ISSUE TITLE
Want a cubing.net subdomain?

### ISSUE THREAD

**Issue by lgarron** [crisszkutnik/fewestmoves-client#12]
If you have plans for your own domain, feel free to stick with that. But if you'd like, say, `fmc-weekly.cubing.net` pointed at your Heroku instance, let me know!

**Comment by crisszkutnik** [comment]
We were not looking forward to getting our own domain so of course I accept your offer! `fmc-weekly.cubing.net` certainly looks better and is easier to remember than what we have right now.

Would you mind emailing me with the details so we can make this work?

**Comment by lgarron** [comment]
It looks pretty simple: https://devcenter.heroku.com/articles/custom-domains

I've set a CNAME from `fmc-weekly.cubing.net` to `fewestmoves.herokudns.com`. Could you try adding the domain in Heroku?

**Comment by crisszkutnik** [comment]
Already added the domain to Heroku. I'll email you the DNS target that Heroku gave me (I guess that it is not supposed to be public) so you can set it as CNAME.

If you need anything else just let me know

**Comment by crisszkutnik** [comment]
Working perfectly! Thanks for everything!
